[package]
name = "signer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8"
hex = "0.4.3"
ic-cdk = "0.7"
serde = "1.0.195"

[dev-dependencies]
k256 = { version = "0.12.0", features = ["ecdsa"] }
